// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Sketch = { id: number, name: string, data: any[], creator: string, creation_time_unix: number, };