// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserRegisterWeb = { username: string, email: string, google_id: string | null, password: string, birthday_date_ymd: [number, number, number], grade: number, };